CREATE TABLE KK 
(
  ID NUMBER(5) NOT NULL 
, NOMBRE VARCHAR2(50) NOT NULL 
, APELLIDOS VARCHAR2(20) 
, EMAIL VARCHAR2(25) 
, FECHA DATE 
, CONSTRAINT KK_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE KK
ADD CONSTRAINT KK_UK1 UNIQUE 
(
  NOMBRE 
, APELLIDOS 
)
ENABLE;

ALTER TABLE KK
ADD CONSTRAINT KK_CHK1 CHECK 
(fecha < sysdate)
ENABLE;
/

SELECT * FROM EMP_DETAILS_VIEW V join JOB_HISTORY H ON V.EMPLOYEE_ID = H.EMPLOYEE_ID
--WHERE CITY = 'Toronto'
;
SELECT * FROM VIDA_LABORAL;

CREATE VIEW VIDA_LABORAL AS
SELECT  E.FIRST_NAME || ' ' || E.LAST_NAME NOMBRE_EMPLEADO, 
    E.HIRE_DATE START_DATE, null END_DATE,  
    J.JOB_TITLE, 
    NVL(D.DEPARTMENT_NAME, '(SIN DEPARTAMENTO)') DEPARTMENT_NAME
FROM EMPLOYEES E 
    JOIN JOBS J ON J.JOB_ID = E.JOB_ID
    LEFT JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM JOB_HISTORY)
UNION
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME NOMBRE_EMPLEADO, 
    START_DATE, END_DATE,  
    JOB_TITLE, 
    D.DEPARTMENT_NAME
FROM EMPLOYEES E 
    JOIN JOB_HISTORY H ON E.EMPLOYEE_ID = H.EMPLOYEE_ID
    JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = H.DEPARTMENT_ID
    JOIN JOBS J ON J.JOB_ID = H.JOB_ID
UNION
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME NOMBRE_EMPLEADO, 
    START_DATE, END_DATE,  
    JOB_TITLE, 
    D.DEPARTMENT_NAME
FROM EMPLOYEES E 
    JOIN (SELECT EMPLOYEE_ID, MAX(START_DATE) + 1 START_DATE, NULL END_DATE,
        (SELECT JOB_ID FROM EMPLOYEES E WHERE E.EMPLOYEE_ID = H.EMPLOYEE_ID) JOB_ID,
        (SELECT DEPARTMENT_ID FROM EMPLOYEES E WHERE E.EMPLOYEE_ID = H.EMPLOYEE_ID) DEPARTMENT_ID
    FROM JOB_HISTORY H 
    GROUP BY EMPLOYEE_ID
    ) H ON E.EMPLOYEE_ID = H.EMPLOYEE_ID
    JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = H.DEPARTMENT_ID
    JOIN JOBS J ON J.JOB_ID = H.JOB_ID

ORDER BY 1, START_DATE
;