INSERT INTO ALUMNO.EMPLOYEES
(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(EMPLOYEES_SEQ.NEXTVAL, 'PEPITO', 'GRILLO', 'pgrillo', '555 000 000',TO_CHAR(sysdate, 'DD/Mon/RR'), 'AD_PRES', 22000, null, null, 210);
/
SELECT * FROM EMPLOYEES ORDER BY EMPLOYEE_ID DESC;
SELECT EMPLOYEES_SEQ.CURRVAL FROM DUAL;
/
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 208;
SELECT * FROM JOB_HISTORY WHERE EMPLOYEE_ID = 208;
/
UPDATE EMPLOYEES
SET EMAIL = UPPER(EMAIL), SALARY = (SELECT AVG(SALARY) FROM EMPLOYEES) * 1.1, DEPARTMENT_ID = 230
WHERE EMPLOYEE_ID = 208;
/
-- COMMIT;
DELETE FROM JOB_HISTORY WHERE EMPLOYEE_ID = 208;
ROLLBACK;
DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = 208;

DELETE FROM EMPLOYEES;
UPDATE EMPLOYEES
SET EMAIL = UPPER(EMAIL), SALARY = (SELECT AVG(SALARY) FROM EMPLOYEES) * 1.1;