SELECT COUNTRY_ID, COUNTRY_NAME, REGION_NAME, c.REGION_ID
FROM REGIONS R, COUNTRIES C
WHERE (R.REGION_ID = C.REGION_ID OR C.REGION_ID IS NULL) AND R.REGION_NAME IN ('Europe', 'Asia') 
;
/
SELECT * 
FROM EMPLOYEES;
/
SELECT COUNTRY_ID, COUNTRY_NAME, REGION_NAME
FROM REGIONS R NATURAL JOIN COUNTRIES C 
WHERE R.REGION_NAME IN ('Europe', 'Asia')
;
SELECT employee_id, first_name, job_id, job_title
from employees NATURAL JOIN jobs;
/
SELECT COUNTRY_ID, COUNTRY_NAME, REGION_NAME
FROM REGIONS R 
    INNER JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
WHERE R.REGION_NAME IN ('Europe', 'Asia')
;
/
SELECT *
FROM REGIONS R 
    INNER JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
WHERE R.REGION_NAME IN ('Europe', 'Asia')
;
/
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME NOMBRE, C.COUNTRY_NAME
FROM REGIONS R 
    INNER JOIN COUNTRIES C ON R.REGION_ID = C.REGION_ID
    INNER JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID
    INNER JOIN DEPARTMENTS D ON D.LOCATION_ID = L.LOCATION_ID
    INNER JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE R.REGION_NAME IN ('Europe')
;

SELECT  E.FIRST_NAME || ' ' || E.LAST_NAME NOMBRE_EMPLEADO, J.FIRST_NAME || ' ' || J.LAST_NAME NOMBRE_EMPLEADO
FROM EMPLOYEES E
    INNER JOIN EMPLOYEES J ON E.MANAGER_ID = J.EMPLOYEE_ID
;

SELECT D.*, E.*
FROM DEPARTMENTS D 
    LEFT JOIN EMPLOYEES E ON D.MANAGER_ID = E.EMPLOYEE_ID
ORDER BY 1
;
SELECT D.*, E.*
FROM DEPARTMENTS D 
    RIGHT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
ORDER BY 1
;
SELECT D.*, E.*
FROM DEPARTMENTS D 
    FULL JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
ORDER BY 1
;